###
GET http://localhost:4000/api/people

###
POST http://localhost:4000/api/people
Content-Type: application/json

{
    "name" : "Nixit"
}

###
GET http://localhost:4000/api/people/1

###
PUT http://localhost:4000/api/people/1
Content-Type: application/json

{
    "name":"parth-updated"
}

###
DELETE http://localhost:4000/api/people/1